use std::fmt;

/// Text generated by a platform composition service. Preedit is presentation only;
/// committed text is the single edit path for an active composition.
#[derive(Clone, PartialEq, Eq)]
pub enum TextInputEvent {
    Preedit {
        text: String,
        selection: Option<(usize, usize)>,
    },
    Commit(String),
    Cancel,
}

impl fmt::Debug for TextInputEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Preedit { text, selection } => f
                .debug_struct("Preedit")
                .field("byte_len", &text.len())
                .field("selection", selection)
                .finish(),
            Self::Commit(text) => f
                .debug_struct("Commit")
                .field("byte_len", &text.len())
                .finish(),
            Self::Cancel => f.write_str("Cancel"),
        }
    }
}
