// @generated by telorgon-shader-build; do not edit.

pub(crate) const BUNDLE_INTERFACE_MAJOR: u32 = 4;
pub(crate) const BUNDLE_INTERFACE_MINOR: u32 = 2;
pub(crate) const BUNDLE_HASH: &str =
    "252c189c3758d58bb4bbfa9b8c7c9adb027279374d217e51daf1b9812193ca06";
pub(crate) const BOX_VERTEX_HASH: &str =
    "74a5ca1a74dade29acd48781047899fd7ae626e32c39ccd49862134b011ecbfe";
pub(crate) const BOX_VERTEX: &[u8] = include_bytes!("shaders/vulkan/box.vert.spv");
pub(crate) const BOX_FRAGMENT_HASH: &str =
    "87bcfb6a83f52c588060de8c155e96298e98ee5f33b7608c8273a76f4aee1813";
pub(crate) const BOX_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/box.frag.spv");
pub(crate) const GLYPH_VERTEX_HASH: &str =
    "deaec55e693a5a735813197cee82c05b283f84587b7131d57def08919ec4331a";
pub(crate) const GLYPH_VERTEX: &[u8] = include_bytes!("shaders/vulkan/glyph.vert.spv");
pub(crate) const GLYPH_FRAGMENT_HASH: &str =
    "7670b58770c921f6c8188004314a88743e8259292f7e73e2652bc716fb9d00bb";
pub(crate) const GLYPH_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/glyph.frag.spv");
pub(crate) const IMAGE_VERTEX_HASH: &str =
    "0e78d740032e2754466bc6750bdca100dde5fbd0411e2a98b6bea5e9852babb3";
pub(crate) const IMAGE_VERTEX: &[u8] = include_bytes!("shaders/vulkan/image.vert.spv");
pub(crate) const IMAGE_FRAGMENT_HASH: &str =
    "801d011e7836d1e2d9c3bf42912c4778146eec05730bd501035568535f387e12";
pub(crate) const IMAGE_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/image.frag.spv");
pub(crate) const MATERIAL_VERTEX_HASH: &str =
    "783af7da04c758dc2db03d1187818f7a77548101504d07d1f29a8314a806fe3c";
pub(crate) const MATERIAL_VERTEX: &[u8] = include_bytes!("shaders/vulkan/material.vert.spv");
pub(crate) const MATERIAL_FRAGMENT_HASH: &str =
    "9081901c6da5270cfd18ab0f8a873f299a7c66a3b0c169980cde18c1013c454e";
pub(crate) const MATERIAL_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/material.frag.spv");
pub(crate) const LIQUID_VERTEX_HASH: &str =
    "582ccea1c9998d75b40e6acbd65c73b3fcdd21f1ddf6329cfa0951a90a6cd785";
pub(crate) const LIQUID_VERTEX: &[u8] = include_bytes!("shaders/vulkan/liquid.vert.spv");
pub(crate) const LIQUID_FRAGMENT_HASH: &str =
    "cc70f66c8ffad0c76afd8beccd722f0170b037c1d89d5cf8b246430dc07c0043";
pub(crate) const LIQUID_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/liquid.frag.spv");
