// @generated by telorgon-shader-build; do not edit.

pub(crate) const BUNDLE_INTERFACE_MAJOR: u32 = 4;
pub(crate) const BUNDLE_INTERFACE_MINOR: u32 = 4;
pub(crate) const BUNDLE_HASH: &str =
    "c4c478599e885620ac28b87f0f69c38db7d1ba4b03669c202eaffce3e6d2cd7f";
pub(crate) const BOX_VERTEX_HASH: &str =
    "74a5ca1a74dade29acd48781047899fd7ae626e32c39ccd49862134b011ecbfe";
pub(crate) const BOX_VERTEX: &[u8] = include_bytes!("shaders/vulkan/box.vert.spv");
pub(crate) const BOX_FRAGMENT_HASH: &str =
    "87bcfb6a83f52c588060de8c155e96298e98ee5f33b7608c8273a76f4aee1813";
pub(crate) const BOX_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/box.frag.spv");
pub(crate) const GLYPH_VERTEX_HASH: &str =
    "deaec55e693a5a735813197cee82c05b283f84587b7131d57def08919ec4331a";
pub(crate) const GLYPH_VERTEX: &[u8] = include_bytes!("shaders/vulkan/glyph.vert.spv");
pub(crate) const GLYPH_FRAGMENT_HASH: &str =
    "7670b58770c921f6c8188004314a88743e8259292f7e73e2652bc716fb9d00bb";
pub(crate) const GLYPH_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/glyph.frag.spv");
pub(crate) const IMAGE_VERTEX_HASH: &str =
    "0e78d740032e2754466bc6750bdca100dde5fbd0411e2a98b6bea5e9852babb3";
pub(crate) const IMAGE_VERTEX: &[u8] = include_bytes!("shaders/vulkan/image.vert.spv");
pub(crate) const IMAGE_FRAGMENT_HASH: &str =
    "c517924d1dd1d086e8f041d9966e683d78258f0018668ee524a40f05c46586b8";
pub(crate) const IMAGE_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/image.frag.spv");
pub(crate) const MATERIAL_VERTEX_HASH: &str =
    "783af7da04c758dc2db03d1187818f7a77548101504d07d1f29a8314a806fe3c";
pub(crate) const MATERIAL_VERTEX: &[u8] = include_bytes!("shaders/vulkan/material.vert.spv");
pub(crate) const MATERIAL_FRAGMENT_HASH: &str =
    "9081901c6da5270cfd18ab0f8a873f299a7c66a3b0c169980cde18c1013c454e";
pub(crate) const MATERIAL_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/material.frag.spv");
pub(crate) const LIQUID_VERTEX_HASH: &str =
    "723a6f6c78547285b259a27b70662cd099ca1de03aef8c386ddab111cc0a7834";
pub(crate) const LIQUID_VERTEX: &[u8] = include_bytes!("shaders/vulkan/liquid.vert.spv");
pub(crate) const LIQUID_FRAGMENT_HASH: &str =
    "54df50039ea4a6f8337db15cd147dd3d17b1cd458baf75f3571913bbcb4dce6a";
pub(crate) const LIQUID_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/liquid.frag.spv");
pub(crate) const BLUR_VERTEX_HASH: &str =
    "783af7da04c758dc2db03d1187818f7a77548101504d07d1f29a8314a806fe3c";
pub(crate) const BLUR_VERTEX: &[u8] = include_bytes!("shaders/vulkan/blur.vert.spv");
pub(crate) const BLUR_FRAGMENT_HASH: &str =
    "61e9d7a37fd6bc569f9a929db4b792f1567a62383a02e4c14fc24a2da796f755";
pub(crate) const BLUR_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/blur.frag.spv");
